# Generated by Django 3.0.4 on 2020-05-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pics',
            name='category',
            field=models.CharField(blank=True, choices=[('trad', 'trad'), ('accessories', 'accessories'), ('jeans', 'jeans')], max_length=50, null=True),
        ),
    ]
